services:
  weather_information_export:
    image: weather_information_export:0.1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      OPEN_WEATHER_MAP_API_KEY: $OPEN_WEATHER_MAP_API_KEY
      GOOGLE_APPLICATION_CREDENTIALS: '/credentials/credentials.json'
      LATITUDE: '48.8012045'
      LONGITUDE: '2.4309703'
      TABLE_ID: 'weather-433510.datalake_prod.weather_data'
    volumes:
      # Source code
      - ./src/job:/opt/program/job
      - ~/CREDS/PERSONAL/WEATHER/credentials.json:/credentials/credentials.json